---
# Site settings
baseurl: ""
description: "Northside Strata Pty Ltd"
email: "info@northsidestrata.com.au"
title: "Northside Strata"
url: "http://northsidestrata.com.au"

# Build settings
encoding: "utf-8"
exclude:
    # Directories
    # Files
    - "_config.yml"
    - "CNAME"
    - "LICENSE.md"
    - "README.md"
lsi: false
port: 3333
safe: true
timezone: "Australia/Sydney"
